-- RotaSegura 1.0 Beta - PostgreSQL/PostGIS + RLS
create extension if not exists pgcrypto;
create extension if not exists postgis;

create type public.member_role as enum ('owner','admin','dispatcher','driver','viewer');
create type public.incident_status as enum ('Em validação','Monitorada','Confirmada','Descartada');
create type public.incident_source as enum ('OFICIAL','COMUNIDADE');
create type public.severity_level as enum ('baixa','media','alta');

create table public.organizations (
 id uuid primary key default gen_random_uuid(),
 name text not null,
 created_at timestamptz not null default now()
);
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text,
 phone text,
 created_at timestamptz not null default now()
);
create table public.memberships (
 organization_id uuid not null references public.organizations(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 role public.member_role not null default 'viewer',
 created_at timestamptz not null default now(),
 primary key (organization_id,user_id)
);
create table public.vehicles (
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete cascade,
 plate text not null,
 model text not null,
 axles integer,
 gross_weight_kg integer,
 height_m numeric(5,2),
 width_m numeric(5,2),
 length_m numeric(6,2),
 status text not null default 'Disponível',
 created_at timestamptz not null default now(),
 unique(organization_id,plate)
);
create table public.drivers (
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,
 name text not null,
 cnh_hash text,
 phone text,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table public.trips (
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null references public.organizations(id) on delete cascade,
 vehicle_id uuid references public.vehicles(id) on delete set null,
 driver_id uuid references public.drivers(id) on delete set null,
 origin_label text not null,
 destination_label text not null,
 origin geography(point,4326),
 destination geography(point,4326),
 planned_route geometry(linestring,4326),
 status text not null default 'Planejada',
 risk_score numeric(7,2) default 0,
 started_at timestamptz,
 finished_at timestamptz,
 created_at timestamptz not null default now()
);
create table public.incidents (
 id uuid primary key default gen_random_uuid(),
 organization_id uuid references public.organizations(id) on delete set null,
 reporter_id uuid references auth.users(id) on delete set null,
 type text not null,
 road text not null,
 place text,
 description text not null,
 lat double precision,
 lon double precision,
 location geography(point,4326) generated always as (case when lat is null or lon is null then null else st_setsrid(st_makepoint(lon,lat),4326)::geography end) stored,
 severity public.severity_level not null default 'media',
 source public.incident_source not null default 'COMUNIDADE',
 status public.incident_status not null default 'Em validação',
 official_source text,
 official_reference text,
 confirmations integer not null default 0 check(confirmations >= 0),
 updated text default 'agora',
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index incidents_location_gix on public.incidents using gist(location);
create index trips_route_gix on public.trips using gist(planned_route);
create index incidents_status_idx on public.incidents(status,created_at desc);

create table public.incident_confirmations (
 incident_id uuid not null references public.incidents(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 confirmation boolean not null,
 created_at timestamptz not null default now(),
 primary key(incident_id,user_id)
);
create table public.audit_log (
 id bigint generated by default as identity primary key,
 organization_id uuid references public.organizations(id) on delete set null,
 actor_id uuid references auth.users(id) on delete set null,
 action text not null,
 entity_type text not null,
 entity_id text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.vehicles enable row level security;
alter table public.drivers enable row level security;
alter table public.trips enable row level security;
alter table public.incidents enable row level security;
alter table public.incident_confirmations enable row level security;
alter table public.audit_log enable row level security;

create or replace function public.is_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.memberships m where m.organization_id=org and m.user_id=auth.uid());
$$;
create or replace function public.has_role(org uuid, roles public.member_role[]) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.memberships m where m.organization_id=org and m.user_id=auth.uid() and m.role=any(roles));
$$;

create policy "profile self" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "org members read" on public.organizations for select using(public.is_member(id));
create policy "members see memberships" on public.memberships for select using(public.is_member(organization_id));
create policy "admins manage vehicles" on public.vehicles for all using(public.is_member(organization_id)) with check(public.has_role(organization_id,array['owner','admin','dispatcher']::public.member_role[]));
create policy "members read drivers" on public.drivers for select using(public.is_member(organization_id));
create policy "admins manage drivers" on public.drivers for all using(public.has_role(organization_id,array['owner','admin','dispatcher']::public.member_role[])) with check(public.has_role(organization_id,array['owner','admin','dispatcher']::public.member_role[]));
create policy "members read trips" on public.trips for select using(public.is_member(organization_id));
create policy "dispatch manage trips" on public.trips for all using(public.has_role(organization_id,array['owner','admin','dispatcher']::public.member_role[])) with check(public.has_role(organization_id,array['owner','admin','dispatcher']::public.member_role[]));
create policy "authenticated read confirmed incidents" on public.incidents for select to authenticated using(status in ('Confirmada','Monitorada') or reporter_id=auth.uid() or (organization_id is not null and public.is_member(organization_id)));
create policy "authenticated report incidents" on public.incidents for insert to authenticated with check(source='COMUNIDADE' and reporter_id=auth.uid());
create policy "own confirmations" on public.incident_confirmations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "org audit read admins" on public.audit_log for select using(organization_id is not null and public.has_role(organization_id,array['owner','admin']::public.member_role[]));

-- Realtime: habilite essas tabelas também no painel Supabase > Database > Replication.
