'use client';
import {useEffect,useRef,useState} from 'react';
import {Layers3,LocateFixed,TriangleAlert,CloudRain,Navigation,Route as RouteIcon,ShieldCheck} from 'lucide-react';
import type {Incident} from '@/lib/data';

export type RouteResult={distanceKm:number;durationMin:number;geometry:{type:'LineString';coordinates:number[][]};origin:{label:string;lon:number;lat:number};destination:{label:string;lon:number;lat:number};source:string;riskScore?:number;risk?:'baixo'|'moderado'|'alto';alternatives?:number;vehicle?:string};
function popupNode(i:Incident){const root=document.createElement('div');root.className='map-popup';const meta=document.createElement('div');meta.className='popup-meta';meta.textContent=i.source==='OFICIAL'?'OFICIAL':'COMUNIDADE';const b=document.createElement('b');b.textContent=i.type;const span=document.createElement('span');span.textContent=`${i.road}${i.place?` · ${i.place}`:''}`;const small=document.createElement('small');small.textContent=i.status;root.append(meta,b,span,small);return root}

export default function ProfessionalMap({incidents,initialRoute}:{incidents:Incident[];initialRoute?:RouteResult|null}){
 const el=useRef<HTMLDivElement>(null);const mapRef=useRef<any>(null);const markers=useRef<any[]>([]);const [ready,setReady]=useState(false);const [maplibre,setMaplibre]=useState<any>(null);const [showIncidents,setShowIncidents]=useState(true);
 useEffect(()=>{let cancelled=false;let map:any;(async()=>{const m=(await import('maplibre-gl')).default;await import('maplibre-gl/dist/maplibre-gl.css');if(cancelled||!el.current)return;setMaplibre(m);map=new m.Map({container:el.current,style:process.env.NEXT_PUBLIC_MAP_STYLE_URL||'https://tiles.openfreemap.org/styles/liberty',center:[-51.53,-29.18],zoom:8.35,pitch:15,bearing:-3,attributionControl:false,maxPitch:55});mapRef.current=map;map.addControl(new m.NavigationControl({showCompass:false}),'bottom-right');map.addControl(new m.ScaleControl({unit:'metric'}),'bottom-left');map.addControl(new m.AttributionControl({compact:true}),'bottom-left');map.on('load',()=>setReady(true));})();return()=>{cancelled=true;markers.current.forEach(x=>x.remove());if(map)map.remove()}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready||!maplibre)return;markers.current.forEach(x=>x.remove());markers.current=[];if(!showIncidents)return;incidents.filter(i=>Number.isFinite(i.lon)&&Number.isFinite(i.lat)).forEach(i=>{const e=document.createElement('button');e.type='button';e.className=`risk-marker ${i.severity}`;e.setAttribute('aria-label',`${i.type} em ${i.road}`);e.innerHTML='<span></span>';const popup=new maplibre.Popup({offset:18,closeButton:false,className:'rs-popup'}).setDOMContent(popupNode(i));const mk=new maplibre.Marker({element:e}).setLngLat([i.lon,i.lat]).setPopup(popup).addTo(map);markers.current.push(mk)})},[incidents,ready,maplibre,showIncidents]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready||!initialRoute||!maplibre)return;const id='rs-route';const geo={type:'Feature',properties:{risk:initialRoute.risk||'baixo'},geometry:initialRoute.geometry} as any;const color=initialRoute.risk==='alto'?'#e23c45':initialRoute.risk==='moderado'?'#ef8f21':'#0c9a63';if(map.getSource(id)){(map.getSource(id) as any).setData(geo);map.setPaintProperty('rs-route-line','line-color',color)}else{map.addSource(id,{type:'geojson',data:geo});map.addLayer({id:'rs-route-outline',type:'line',source:id,paint:{'line-color':'#ffffff','line-width':10,'line-opacity':0.94}});map.addLayer({id:'rs-route-line',type:'line',source:id,paint:{'line-color':color,'line-width':5.5,'line-opacity':1}})}const c=initialRoute.geometry.coordinates;if(c.length){const b=c.reduce((bb:any,p:number[])=>bb.extend(p),new maplibre.LngLatBounds(c[0],c[0]));map.fitBounds(b,{padding:{top:88,bottom:105,left:76,right:76},duration:850,maxZoom:12})}},[initialRoute,ready,maplibre]);
 const locate=()=>{if(!navigator.geolocation||!mapRef.current)return;navigator.geolocation.getCurrentPosition(p=>mapRef.current.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:13,duration:900}),()=>{}, {enableHighAccuracy:true,timeout:8000,maximumAge:15000})};
 return <div className="map-pro">
   <div ref={el} className="map-pro-canvas"/>
   <div className="map-top-chip"><span className="pulse"/> Mapa operacional</div>
   <div className="map-tools"><button title="Ocorrências" aria-pressed={showIncidents} onClick={()=>setShowIncidents(v=>!v)}><Layers3 size={18}/></button><button title="Clima"><CloudRain size={18}/></button><button title="Alertas"><TriangleAlert size={18}/></button><button title="Minha localização" onClick={locate}><LocateFixed size={18}/></button></div>
   {initialRoute&&<div className="route-float"><div className="route-float-head"><div className="route-shield"><ShieldCheck size={17}/></div><div><small>ROTA RECOMENDADA</small><b>{initialRoute.origin.label} → {initialRoute.destination.label}</b></div></div><div className="route-float-metrics"><strong>{initialRoute.distanceKm} km</strong><strong>{Math.floor(initialRoute.durationMin/60)}h {initialRoute.durationMin%60}min</strong><em className={`risk-${initialRoute.risk||'baixo'}`}>{initialRoute.risk||'baixo'} risco</em></div><div className="route-float-line"><span><RouteIcon size={14}/> {initialRoute.vehicle||'Perfil logístico'}</span><span><Navigation size={14}/> {initialRoute.alternatives||1} rota(s)</span></div></div>}
   {!ready&&<div className="map-loading"><span className="map-loader"/>Carregando mapa…</div>}
 </div>
}
