-- RotaSegura Professional 2.0 - hardening, tenancy, onboarding, realtime
create extension if not exists pgcrypto;
create extension if not exists postgis;
create extension if not exists unaccent;

-- Extra operational fields
alter table public.organizations add column if not exists slug text;
alter table public.organizations add column if not exists plan text not null default 'professional';
alter table public.organizations add column if not exists active boolean not null default true;
create unique index if not exists organizations_slug_uidx on public.organizations(slug) where slug is not null;

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.vehicles add column if not exists vehicle_type text;
alter table public.vehicles add column if not exists renavam_hash text;
alter table public.vehicles add column if not exists tracker_device_id text;
alter table public.vehicles add column if not exists updated_at timestamptz not null default now();

alter table public.drivers add column if not exists cnh_category text;
alter table public.drivers add column if not exists cnh_expires_at date;
alter table public.drivers add column if not exists updated_at timestamptz not null default now();

alter table public.trips add column if not exists route_provider text;
alter table public.trips add column if not exists distance_km numeric(10,2);
alter table public.trips add column if not exists duration_min integer;
alter table public.trips add column if not exists risk_level text default 'baixo';
alter table public.trips add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.trips add column if not exists updated_at timestamptz not null default now();

create table if not exists public.vehicle_positions (
 id bigint generated by default as identity primary key,
 organization_id uuid not null references public.organizations(id) on delete cascade,
 vehicle_id uuid not null references public.vehicles(id) on delete cascade,
 driver_id uuid references public.drivers(id) on delete set null,
 trip_id uuid references public.trips(id) on delete set null,
 lat double precision not null check(lat between -90 and 90),
 lon double precision not null check(lon between -180 and 180),
 position geography(point,4326) generated always as (st_setsrid(st_makepoint(lon,lat),4326)::geography) stored,
 speed_kmh numeric(6,2),
 heading numeric(6,2),
 accuracy_m numeric(8,2),
 captured_at timestamptz not null default now(),
 created_at timestamptz not null default now()
);
create index if not exists vehicle_positions_position_gix on public.vehicle_positions using gist(position);
create index if not exists vehicle_positions_trip_idx on public.vehicle_positions(trip_id,captured_at desc);

create table if not exists public.official_events (
 id uuid primary key default gen_random_uuid(),
 provider text not null,
 external_id text not null,
 event_type text not null,
 road text,
 title text not null,
 description text,
 severity public.severity_level not null default 'media',
 status text not null default 'active',
 lat double precision,
 lon double precision,
 geometry geometry(geometry,4326),
 source_url text,
 source_published_at timestamptz,
 raw jsonb not null default '{}'::jsonb,
 first_seen_at timestamptz not null default now(),
 last_seen_at timestamptz not null default now(),
 unique(provider,external_id)
);
create index if not exists official_events_geom_gix on public.official_events using gist(geometry);
create index if not exists official_events_status_idx on public.official_events(status,last_seen_at desc);

create table if not exists public.integration_runs (
 id bigint generated by default as identity primary key,
 provider text not null,
 status text not null,
 started_at timestamptz not null default now(),
 finished_at timestamptz,
 records_seen integer not null default 0,
 records_changed integer not null default 0,
 message text,
 metadata jsonb not null default '{}'::jsonb
);

-- Generic updated_at trigger
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ begin
 if not exists(select 1 from pg_trigger where tgname='profiles_updated_at') then create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='vehicles_updated_at') then create trigger vehicles_updated_at before update on public.vehicles for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='drivers_updated_at') then create trigger drivers_updated_at before update on public.drivers for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='trips_updated_at') then create trigger trips_updated_at before update on public.trips for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='incidents_updated_at') then create trigger incidents_updated_at before update on public.incidents for each row execute function public.set_updated_at(); end if;
end $$;

-- First-login corporate bootstrap. The signup page sends full_name + organization_name metadata.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare org_id uuid; org_name text; base_slug text;
begin
 insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))) on conflict(id) do nothing;
 org_name:=nullif(trim(new.raw_user_meta_data->>'organization_name'),'');
 if org_name is not null then
   base_slug:=lower(regexp_replace(unaccent(org_name),'[^a-zA-Z0-9]+','-','g'));
   insert into public.organizations(name,slug) values(org_name,base_slug||'-'||left(replace(new.id::text,'-',''),6)) returning id into org_id;
   insert into public.memberships(organization_id,user_id,role) values(org_id,new.id,'owner');
 end if;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Tenancy RLS for new table
alter table public.vehicle_positions enable row level security;
alter table public.official_events enable row level security;
alter table public.integration_runs enable row level security;

drop policy if exists "members read positions" on public.vehicle_positions;
create policy "members read positions" on public.vehicle_positions for select to authenticated using(public.is_member(organization_id));
drop policy if exists "driver writes positions" on public.vehicle_positions;
create policy "driver writes positions" on public.vehicle_positions for insert to authenticated with check(public.is_member(organization_id));

drop policy if exists "authenticated read official events" on public.official_events;
create policy "authenticated read official events" on public.official_events for select to authenticated using(true);
-- writes to official_events/integration_runs are service-role only (no insert/update policy)

drop policy if exists "admins read integration runs" on public.integration_runs;
create policy "admins read integration runs" on public.integration_runs for select to authenticated using(true);

-- Ensure incident reporter is really the logged user and do not allow community reports to impersonate official providers.
drop policy if exists "authenticated report incidents" on public.incidents;
create policy "authenticated report incidents" on public.incidents for insert to authenticated with check(source='COMUNIDADE' and reporter_id=auth.uid());

-- Atomic confirmation + confidence recalculation
create or replace function public.confirm_incident(p_incident uuid,p_confirm boolean default true)
returns void language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null then raise exception 'unauthenticated'; end if;
 insert into public.incident_confirmations(incident_id,user_id,confirmation) values(p_incident,auth.uid(),p_confirm)
 on conflict(incident_id,user_id) do update set confirmation=excluded.confirmation,created_at=now();
 update public.incidents i set confirmations=(select count(*) from public.incident_confirmations c where c.incident_id=i.id and c.confirmation=true),updated_at=now() where i.id=p_incident;
end $$;
grant execute on function public.confirm_incident(uuid,boolean) to authenticated;

-- Read-only RPC for nearby active risks used by routing services.
create or replace function public.nearby_incidents(p_lon double precision,p_lat double precision,p_radius_m integer default 10000)
returns setof public.incidents language sql stable security definer set search_path=public as $$
 select * from public.incidents where location is not null and status in ('Confirmada','Monitorada','Em validação')
 and st_dwithin(location,st_setsrid(st_makepoint(p_lon,p_lat),4326)::geography,p_radius_m)
 order by created_at desc limit 200;
$$;
grant execute on function public.nearby_incidents(double precision,double precision,integer) to authenticated;

-- Realtime publication (safe if already added)
do $$ begin
 begin alter publication supabase_realtime add table public.incidents; exception when duplicate_object then null; end;
 begin alter publication supabase_realtime add table public.trips; exception when duplicate_object then null; end;
 begin alter publication supabase_realtime add table public.vehicle_positions; exception when duplicate_object then null; end;
 begin alter publication supabase_realtime add table public.official_events; exception when duplicate_object then null; end;
end $$;

-- Transactional trip creation from GeoJSON, keeping PostGIS conversion inside PostgreSQL.
create or replace function public.create_trip(
 p_origin_label text,p_destination_label text,p_origin_lon double precision,p_origin_lat double precision,
 p_destination_lon double precision,p_destination_lat double precision,p_route_geojson jsonb,
 p_distance_km numeric,p_duration_min integer,p_risk_score numeric,p_risk_level text,p_provider text,
 p_vehicle_id uuid default null,p_driver_id uuid default null
) returns uuid language plpgsql security definer set search_path=public as $$
declare org_id uuid; new_id uuid;
begin
 select organization_id into org_id from public.memberships where user_id=auth.uid() and role in ('owner','admin','dispatcher') limit 1;
 if org_id is null then raise exception 'forbidden'; end if;
 insert into public.trips(organization_id,vehicle_id,driver_id,origin_label,destination_label,origin,destination,planned_route,status,risk_score,risk_level,distance_km,duration_min,route_provider,metadata)
 values(org_id,p_vehicle_id,p_driver_id,p_origin_label,p_destination_label,
 st_setsrid(st_makepoint(p_origin_lon,p_origin_lat),4326)::geography,
 st_setsrid(st_makepoint(p_destination_lon,p_destination_lat),4326)::geography,
 st_setsrid(st_geomfromgeojson(p_route_geojson::text),4326),'Planejada',p_risk_score,p_risk_level,p_distance_km,p_duration_min,p_provider,jsonb_build_object('created_by',auth.uid()))
 returning id into new_id;
 return new_id;
end $$;
grant execute on function public.create_trip(text,text,double precision,double precision,double precision,double precision,jsonb,numeric,integer,numeric,text,text,uuid,uuid) to authenticated;
